using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace StudentApi.Services.Implementations
{
    public class PdfService
    {
        public byte[] GenerateStudentReportPdf(StudentReportDto report)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    // HEADER
                    page.Header()
                        .AlignCenter()
                        .Text("Student Report Card")
                        .FontSize(24)
                        .Bold();

                    // CONTENT
                    page.Content().PaddingVertical(20).Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text($"Student Name: {report.StudentName}");
                        col.Item().Text($"Class: {report.ClassName}");
                        col.Item().Text($"Rank: {report.Rank}");
                        col.Item().Text($"Average Score: {report.AverageScore}");
                        col.Item().Text($"Status: {report.Status}");

                        col.Item().PaddingTop(20);

                        // TABLE
                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(4);
                                columns.RelativeColumn(1);
                            });

                            // HEADER
                            table.Header(header =>
                            {
                                header.Cell().Element(CellStyle)
                                    .Text("Course")
                                    .Bold();

                                header.Cell().Element(CellStyle)
                                    .Text("Score")
                                    .Bold();
                            });

                            // DATA
                            foreach (var course in report.Courses)
                            {
                                table.Cell().Element(CellStyle)
                                    .Text(course.CourseName);

                                table.Cell().Element(CellStyle)
                                    .Text(course.Score.ToString());
                            }
                        });
                    });

                    // FOOTER
                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Student Management System");
                });
            });

            return document.GeneratePdf();
        }



// NEW METHOD: GENERATE STUDENTS LIST PDF
public byte[] GenerateStudentsListPdf(
    List<StudentDto> students)
{
    var document = Document.Create(container =>
    {
        container.Page(page =>
        {
            page.Margin(30);

            // HEADER
            page.Header()
                .AlignCenter()
                .Text("Registered Students")
                .FontSize(24)
                .Bold();

            // CONTENT
            page.Content().PaddingVertical(20).Column(col =>
            {
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(1);
                        columns.RelativeColumn(3);
                        columns.RelativeColumn(2);
                        columns.RelativeColumn(2);
                    });

                    // TABLE HEADER
                    table.Header(header =>
                    {
                        header.Cell().Element(CellStyle)
                            .Text("ID").Bold();

                        header.Cell().Element(CellStyle)
                            .Text("Name").Bold();

                        header.Cell().Element(CellStyle)
                            .Text("Gender").Bold();

                        header.Cell().Element(CellStyle)
                            .Text("Class").Bold();
                    });

                    // TABLE DATA
                    foreach (var student in students)
                    {
                        table.Cell().Element(CellStyle)
                            .Text(student.StudentId.ToString());

                        table.Cell().Element(CellStyle)
                            .Text(student.FullName);

                        table.Cell().Element(CellStyle)
                            .Text(student.Gender);

                        table.Cell().Element(CellStyle)
                            .Text(student.ClassName);
                    }
                });
            });

            // FOOTER
            page.Footer()
                .AlignCenter()
                .Text($"Total Students: {students.Count}");
        });
    });

    return document.GeneratePdf();
}

public byte[] GenerateStudentIdCardPdf(StudentDto student)
{
    var document = Document.Create(container =>
    {
        container.Page(page =>
        {
            page.Size(400, 250);

            page.Margin(10);

            page.Content().Border(2).Column(col =>
            {
                // HEADER
                col.Item().Background("#0B5ED7")
                    .Padding(10)
                    .AlignCenter()
                    .Text("STUDENT ID CARD")
                    .FontColor(Colors.White)
                    .FontSize(20)
                    .Bold();

                // BODY
                col.Item().Padding(15).Column(body =>
                {
                    body.Spacing(8);

                    body.Item().Text(
                        $"Name: {student.FullName}");

                    body.Item().Text(
                        $"Student Code: {student.StudentCode}");

                    body.Item().Text(
                        $"Gender: {student.Gender}");

                    body.Item().Text(
                        $"Class: {student.ClassName}");
                });

         col.Item().Background("#EEEEEE")
                    .Padding(5)
                    .AlignCenter()
                    .Text("Abdisa Primary School");
            });
        });
    });

    return document.GeneratePdf();
}

        private static IContainer CellStyle(IContainer container)
        {
            return container
                .Border(1)
                .Padding(5);
        }
    }
}